CREATE TABLE items (
	id INT AUTO_INCREMENT PRIMARY KEY,
	code VARCHAR(50) NOT NULL,
	content TEXT NOT NULL,
	location VARCHAR(2000) NOT NULL DEFAULT '',
	done TINYINT NOT NULL DEFAULT 0,
	done_by VARCHAR(100) NULL,
	done_at DATETIME NULL,
	created_at DATETIME NOT NULL DEFAULT (UTC_TIMESTAMP()),
	updated_at DATETIME NOT NULL DEFAULT (UTC_TIMESTAMP())
) DEFAULT CHARSET = utf8mb4;

CREATE TABLE item_events (
	id INT AUTO_INCREMENT PRIMARY KEY,
	item_id INT NOT NULL,
	type VARCHAR(20) NOT NULL,
	`by` VARCHAR(100) NOT NULL,
	note VARCHAR(2000) NOT NULL DEFAULT '',
	created_at DATETIME NOT NULL DEFAULT (UTC_TIMESTAMP()),
	FOREIGN KEY (item_id) REFERENCES items (id) ON DELETE CASCADE
) DEFAULT CHARSET = utf8mb4;

CREATE TABLE images (
	id CHAR(36) PRIMARY KEY,
	item_id INT NOT NULL,
	event_id INT NULL,
	content_type VARCHAR(100) NOT NULL,
	created_at DATETIME NOT NULL DEFAULT (UTC_TIMESTAMP()),
	FOREIGN KEY (item_id) REFERENCES items (id) ON DELETE CASCADE,
	FOREIGN KEY (event_id) REFERENCES item_events (id) ON DELETE CASCADE
) DEFAULT CHARSET = utf8mb4;
